# Generated by Django 5.0.7 on 2024-07-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_submission_analysis_remove_submission_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='example_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
