# Generated by Django 5.0.7 on 2024-07-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_problem_example_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem', to='api.category'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem', to='api.subcategory'),
        ),
    ]
